# Generated by Django 6.1 on 2026-09-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=15)),
                ("hobbies", models.CharField(blank=True, max_length=255)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("india", "India"),
                            ("australia", "Australia"),
                            ("usa", "USA"),
                        ],
                        default="india",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
