# Generated by Django 6.1 on 2026-09-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_person_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.RemoveField(
            model_name="person",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="person",
            name="lastname",
        ),
        migrations.RemoveField(
            model_name="person",
            name="password",
        ),
    ]
