# Generated by Django 6.1 on 2026-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_person_email_remove_person_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
